name: angular_components_example
description: An example app using the angular_components package.
environment:
  sdk: '>=1.24.0 <2.0.0-dev.infinity'
dependencies:
  angular: 4.0.0-alpha+2
  angular_components: 0.6.0-alpha+2
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
dev_dependencies:
  angular_test: ^1.0.0-beta+5
  test: ^0.12.0
transformers:
- angular:
    entry_points: web/main.dart
- angular/transform/reflection_remover:
    $include:
      - test/**_test.dart
      - web/main.dart
- test/pub_serve:
    $include: test/**_test.dart
- $dart2js:
    commandLineOptions: [--trust-type-annotations, --trust-primitives, --show-package-warnings, --dump-info]
- dart_to_js_script_rewriter
